### ISSUE TITLE
Not able to run because of library compatible issue

### ISSUE THREAD

**Issue by ragudiko** [IBM/ensure-loan-fairness-aif360#23]
I get below error when importing libraries
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb

**Comment by stevemar** [comment]
@ragudiko are you running this on watson studio or locally? also, what version of python are you using?

**Comment by ragudiko** [comment]
@stevemart : When I run in watson studio-->notebook, I get this error.
When I import same notebook into local(anaconda/virtual environment) it runs successfully. But I have one observation in local machine Which I raised to research team here.
The below code execution gives different value **-0.136480** instead of **0.001276**. I am executing notebook locally after cloning github repo.
 
metric_transf_train = BinaryLabelDatasetMetric(dataset_transf_train,
                                              unprivileged_groups=unprivileged_groups,
                                              privileged_groups=privileged_groups)
display(Markdown("#### Transformed training dataset"))
print("Difference in mean outcomes between unprivileged and privileged groups = %f" % metric_transf_train.mean_difference())

**Comment by ragudiko** [comment]
@stevemart : I just got belowupdate from Kala Kannan(kalapriya.kannan@in.ibm.com)
email copy:
I checked with Karthikeyan(knatesa@us.ibm.com). Looks like specifically this algorithms uses a random seed and because of this the notebook demo might have an issue. His advice is to use a different algorithm if it is going to be notebook and this has to be handled by having more partitions.

**Comment by scottdangelo** [comment]
@ragudiko I have started with a new project and notebook in Watson studio, using Default Python 3.5 kernel, and I cannot reproduce your error.
Can you tell me which cell you ran that produced the Runtime Error?

**Comment by ragudiko** [comment]
![ai-fairness-library-issue](https://user-images.githubusercontent.com/28623113/46681679-64a35d80-cc09-11e8-8aa1-32fa2bb5c176.png)

I am just using default configuration option.

**Comment by scottdangelo** [comment]
Try using a python kernel without Spark, please. 
Also, can you cut and paste (not screenshot) the entire stack trace?

**Comment by ragudiko** [comment]
Thanks Scott, I can run notebook without errors once I chose python kernel without Spark as suggested by you. Why it fails when used the first default option- python with spark? It will be good to mention right option in code pattern.
 
But the difference in mean outcomes between unprivileged and privileged groups = -0.013180 is not the expected value mentioned in code pattern.

**Comment by ragudiko** [comment]
We use same python **3.5** version with spark or without spark then how does library version differ when used with spark?

**Comment by scottdangelo** [comment]
That would be a question for someone in Watson Studio. Watson Studio provides various environments, and the internal implementations, libraries, and details are not something I know about.

**Comment by scottdangelo** [comment]
Solution is to use Python 3.5 kernel environment with Watson Studio, not the Spark kernel.
