### ISSUE TITLE
online demo - 404 Error

### ISSUE THREAD

**Issue by XReyRobert-IBM** [IBM/ensure-loan-fairness-aif360#24]
Live demo is broken

**Comment by scottdangelo** [comment]
I am able to view the demo at this URL:
http://aif360.mybluemix.net/data

This is the link in this repository, under `Links` and also on the main [code pattern page](https://developer.ibm.com/patterns/ensuring-fairness-when-processing-loan-applications) under [View the demo](http://aif360.mybluemix.net/data).

**Comment by XReyRobert-IBM** [comment]
Right, earlier it was a 404.
