### ISSUE TITLE
The watson project creation should be more detailed 

### ISSUE THREAD

**Issue by thomassuedbroecker** [IBM/ensure-loan-fairness-aif360#26]
Maybe you can add more concrete, how to create a Watson Studio Project into your readme?

Reason: When you create a Watson Studio Project, you have **many options/project types** to create a projects.
The best project type which does fit is the **data science**, this project should contain data and notebooks. When you create such project, you will be a little bit confused, because there is **no option** to **add notebooks** as defined in the instructions. You can create a notebook directly using **tools->notebook**  and then you can add the notebook to your project, with the given **url**.

BTW: Also it would be good, if you show which *runtime* should be used for the notebook for example *Default Python 3.5 Free (1 vCPU and 4 GB RAM)* .  With this configuration the installation of spark and the needed additional packages worked for me.

**Comment by timroster** [comment]
Using that runtime today: _Default Python 3.5 Free (1 vCPU and 4 GB RAM_ - I was getting a `API version 0xc but this version of numpy is 0xb` error in Step 5 - so I added a `!pip install numpy=1.14` just before `import numpy` in Step 2 and then the notebook ran through to completion

**Comment by stephanbm** [comment]
We got ours down. Where’s yours?
